server:
  port: 5000
  shutdown: graceful
  error:
    include-stacktrace: never

spring:
  application:
    name: transaction

logging:
  level:
    root: INFO

open:
  api:
    url: https://apisandbox.openbankproject.com/
